on:
  push:
    branches:
      - main
jobs:
  build_ported_tools:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - run: tools/build.sh
  strip_clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: tools/strip-clang.sh
  strip_swift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: tools/strip-swift.sh
