on:
  push:
    tags:
      - '*'
jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
  build_ported_tools:
    runs-on: ubuntu-24.04
    needs: create_release
    steps:
      - uses: actions/checkout@v2
      - run: tools/build.sh
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: out/ported-tools-linux-x86_64.tar.xz
          asset_name: ported-tools-linux-x86_64.tar.xz
          asset_content_type: application/x-xz
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: out/ported-tools-linux-x86_64.tar.xz.sha256
          asset_name: ported-tools-linux-x86_64.tar.xz.sha256
          asset_content_type: text/plain
  strip_clang:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - uses: actions/checkout@v2
      - run: tools/strip-clang.sh
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04-stripped.tar.xz
          asset_name: clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04-stripped.tar.xz
          asset_content_type: application/x-xz
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04-stripped.tar.xz.sha256
          asset_name: clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04-stripped.tar.xz.sha256
          asset_content_type: text/plain
  strip_swift:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - uses: actions/checkout@v2
      - run: tools/strip-swift.sh
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: swift-6.2.3-RELEASE-ubuntu22.04-stripped.tar.xz
          asset_name: swift-6.2.3-RELEASE-ubuntu22.04-stripped.tar.xz
          asset_content_type: application/x-xz
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: swift-6.2.3-RELEASE-ubuntu22.04-stripped.tar.xz.sha256
          asset_name: swift-6.2.3-RELEASE-ubuntu22.04-stripped.tar.xz.sha256
          asset_content_type: text/plain
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/xcode:12.4
            ghcr.io/${{ github.repository_owner }}/xcode:12.4-focal
